[project]
name = "pythonproject"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aws-lambda-powertools>=3.31.1",
    "boto3>=1.43.54",
    "boto3-stubs~=1.43.54",
    "cachetools>=7.1.6",
    "pyyaml>=6.0.3",
    "valkey==6.1.1",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "locust>=2.46.3",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
]
[tool.pytest.ini_options]
pythonpath = ["src/RateLimiter"]
testpaths = ["tests"]
markers = [
    "integration: tests requiring external infrastructure"
]