AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Monitoring resources for the Payment Demo

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  LambdaFunctionName:
    Type: String
  LogRetentionDays:
    Type: Number
    Default: 14

Resources:
  #########################################
  # Alarms
  #########################################
  Alarms:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./monitoring/alarms.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        LambdaFunctionName: !Ref LambdaFunctionName

  #########################################
  # Dashboards
  #########################################
  Dashboards:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./monitoring/dashboards.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        LambdaFunctionName: !Ref LambdaFunctionName