AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Monitoring resources (alarms) for the Payment Demo

Parameters:
  Environment:
    Type: String
  ProjectName:
    Type: String
  LambdaFunctionName:
    Type: String
  LambdaConcurrencyWarningThreshold:
    Type: Number
    Default: 8

Resources:

  #########################################################
  # SNS Topic
  #########################################################

  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Environment}-${ProjectName}-alarms"

  #########################################################
  # Lambda error alarm
  #########################################################

  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-${ProjectName}-lambda-errors"
      Namespace: AWS/Lambda
      MetricName: Errors
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      AlarmActions:
        - !Ref AlarmTopic

  #########################################################
  # Lambda duration alarm
  #########################################################

  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-${ProjectName}-lambda-duration"
      Namespace: AWS/Lambda
      MetricName: Duration
      ExtendedStatistic: p95
      Period: 60
      EvaluationPeriods: 3
      DatapointsToAlarm: 2
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      AlarmActions:
        - !Ref AlarmTopic

  #########################################################
  # Lambda throttle alarm
  #########################################################

  LambdaThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-${ProjectName}-lambda-throttles"
      Namespace: AWS/Lambda
      MetricName: Throttles
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      AlarmActions:
        - !Ref AlarmTopic

  #########################################################
  # Lambda concurrency alarm
  #########################################################

  LambdaConcurrencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-${ProjectName}-lambda-concurrency"
      Namespace: AWS/Lambda
      MetricName: ConcurrentExecutions
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: !Ref LambdaConcurrencyWarningThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      AlarmActions:
        - !Ref AlarmTopic

  #########################################################
  # Valkey Unavailable
  #########################################################

  ValkeyUnavailableAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-${ProjectName}-valkey-unavailable"
      Namespace: PaymentDemo
      MetricName: ValkeyUnavailable
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: Environment
          Value: !Ref Environment
      AlarmActions:
        - !Ref AlarmTopic

  #########################################################
  # Valkey Unavailable
  #########################################################

  UnhandledErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-${ProjectName}-unhandled-errors"
      Namespace: PaymentDemo
      MetricName: UnhandledErrors
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: Environment
          Value: !Ref Environment
      AlarmActions:
        - !Ref AlarmTopic

Outputs:
  AlarmTopicArn:
    Value: !Ref AlarmTopic