AWSTemplateFormatVersion: '2010-09-09'
Description: Monitoring resources (log group) for the Payment Demo

Parameters:
  LambdaFunctionName:
    Type: String

  LogRetentionDays:
    Type: Number

Resources:

  #########################################################
  # CloudWatch Log Group
  #########################################################

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunctionName}"
      RetentionInDays: !Ref LogRetentionDays